### ISSUE TITLE
Initial design ~ header/footer ~

### ISSUE THREAD

**Issue by myoortcloud** [myoortcloud/kmu-edx#1]
<b>July 29, 2014</b>
- Home
  ![detail](https://cloud.githubusercontent.com/assets/6212926/3732339/4d494c76-16fa-11e4-826f-edee79f77a26.png)
- Course
  ![detail2](https://cloud.githubusercontent.com/assets/6212926/3732338/4d1995da-16fa-11e4-8de2-fd8a9c5ee0eb.png)

**Comment by myoortcloud** [comment]
July 30, 2014
- Home
  ![detail](https://cloud.githubusercontent.com/assets/6212926/3746126/f0860d1a-17b9-11e4-92f8-d7c9b7bc0003.png)
- Course
  ![detail2](https://cloud.githubusercontent.com/assets/6212926/3746127/f169e062-17b9-11e4-818f-f8bf72012e8e.png)
- 공통 변경사항
  Footer 수정
  로고 표준화 (백터 로고 기반으로)

**Comment by anqsdwe** [comment]
굿굿

**Comment by myoortcloud** [comment]
Aug 6
- Default: Before sign in
  ![signin_1](https://cloud.githubusercontent.com/assets/6212926/3824785/7f3fe52a-1d4c-11e4-8655-689557d98f00.png)
- Default: After sign in
  ![signedin_01](https://cloud.githubusercontent.com/assets/6212926/3824791/8b44b92c-1d4c-11e4-922a-1474aed400ea.png)

To-do: staff button 부분의 여백 수정 필요
- Slim
  ![signedin_1](https://cloud.githubusercontent.com/assets/6212926/3824799/a43becc0-1d4c-11e4-8707-df6405f54755.png)

`
![signedin_2](https://cloud.githubusercontent.com/assets/6212926/3824802/ae40943c-1d4c-11e4-84de-871585cb82bd.png)

**Comment by myoortcloud** [comment]
Aug 12
- sass 컬러 팔레트 커스터마이징 완료.
- 테마 이름 변환 완료.

![courseware1](https://cloud.githubusercontent.com/assets/6212926/3887337/f798f394-21ee-11e4-9b78-d9b7a860fe7c.png)

![colouring](https://cloud.githubusercontent.com/assets/6212926/3887338/f79c6254-21ee-11e4-8f84-e48e58fd855c.png)
- 컬러 팔레트 수정에 따른 courseware, component styles 적용

![index](https://cloud.githubusercontent.com/assets/6212926/3887339/f7a022ae-21ee-11e4-9b38-42b9fee00884.png)
- 미인증 상태에서의 Index 파노라마 교체. (출처는 학교 홈페이지의 항공사진으로 저작권 시비는 없음!)
- To-do: 미인증 상태에서의 Index 파노라마 중앙에 뜨는 문구와 유튭 비디오 부분 제거?
- To-do: 운영서버 적용.

**Comment by myoortcloud** [comment]
Re-forking the edx-theme Repo.
- 사유: 오리지널 stanford 테마를 Branch로 남겨둠.
