### ISSUE TITLE
SSL 적용

### ISSUE THREAD

**Issue by myoortcloud** [myoortcloud/kmu-edx#2]
SSL on nginx

https://www.digitalocean.com/community/tutorials/how-to-create-a-ssl-certificate-on-nginx-for-ubuntu-12-04

**Comment by myoortcloud** [comment]
현재까지 알려진 사항
- 교과부 권고 규정?
- 교과부에서 지원하는 무료 인증서 신청 가능 (보안 담당자분)
  단 모바일에서의 접속이 불안정할 수 있음

**Comment by anqsdwe** [comment]
교수님이 무료 인증서를 신청하여 일단 진행후, 전자정부가 정식으로 상용화되면 유료를 고려해본다고 하셨습니다.

**Comment by anqsdwe** [comment]
금요일날 SSL 관련하여 보안담당자와 얘기해보고 해결해 보겠습니다.

**Comment by anqsdwe** [comment]
1.제 메일로 SSL 신청 매뉴얼과 신청서를보내준다고 하였습니다.

개인적으로 궁금한 점을 물어보았습니다.

SSL은 학교에서 주는 걸 꼭 쓸 필요는 없고, 외부SSL를 써도 된다고 하는데,
edx server_var.yml을 통해 nginx로 ssl 적용할수 있는것 같고,

일단 학교에서 보내준 메일 을 보고 메뉴얼이 어떤식으로 되있는지 봐야겠습니다.

**Comment by anqsdwe** [comment]
@myoortcloud 

참고자료 추가

https://github.com/edx/configuration/wiki/Setting-Up-External-Authentication

http://ydevel.tumblr.com/post/22850778860/configuring-an-https-site-with-django-on-nginx
