### ISSUE TITLE
장고 admin 로컬화

### ISSUE THREAD

**Issue by anqsdwe** [myoortcloud/kmu-edx#4]
호스트에서만 admin이 접속이 되도록 바꿔주어야 합니다.

**Comment by anqsdwe** [comment]
LMS 뿐만 아니라 CMS도 바꿔주어야 합니다.

**Comment by myoortcloud** [comment]
- server-vars.yml

EDXAPP_BOOK_URL: ""
# This needs to be set to localhost
# if xqueue is run on the same server
# as the lms (it's sent in the request)
EDXAPP_SITE_NAME: 'localhost'

-> EDXAPP_SITE_NAME 변수를 수정, begov.kookmin.ac.kr 등으로
-> 수정 후 테스트 요망

**Comment by anqsdwe** [comment]
admin주소는 수정뒤 테스트 성공하였씁니다.
EDXAPP_SITE_NAME 변수는, 메일을 이 계속 안와서 확인이 불가능합니다.
제가 바꿔서 안오는 걸까요..

**Comment by anqsdwe** [comment]
일단, 메일은 안오지만,관리자 측면에서 가입 희망자를해결해야만 하는 절차가 이루어 지게 되기때문에

원하는 방식으로 된것 같습니다.

**Comment by anqsdwe** [comment]
가입 후, 인증 과정을 설명하는 부분을
administrator의 확인을 받아야 한다고 수정하였습니다
