### ISSUE TITLE
Registration: 우측 안내문구 수정

### ISSUE THREAD

**Issue by myoortcloud** [myoortcloud/kmu-edx#6]
![act](https://cloud.githubusercontent.com/assets/6212926/3887393/f3fc126a-21ef-11e4-8f2c-8753d28d0d09.png)

인증방식의 변경으로 인해 Activation link in email 에 관련된 내용 수정

**Comment by anqsdwe** [comment]
하는중입니다.

**Comment by anqsdwe** [comment]
#파일 경로
edx-platform / lms / templates / register-sidebar.html
- 수정 내용
  As part of joining {platform_name}, you will receive an activation email.  You must click on the activation link to complete the process.  Don't see the email?  Check your spam folder and mark {platform_name} emails as 'not spam'.  At {platform_name}, we communicate mostly through email.").format(platform_name=platform_name)}

**Comment by anqsdwe** [comment]
*수정후

("As part of joining {platform_name}, you must wait until administrator confirm your sign up request. If you have any question, contact administrator via e-mail. we communicate mostly through email."

**Comment by myoortcloud** [comment]
"As part of joining {platform_name}, you must wait until administrator confirm your sign up request. If you have any question, contact administrator via e-mail. we communicate mostly through email."

Email address

As part of joining {platform_name}, you will receive an welcome email. Please check your email address is valid. Don't see the email?  Check your spam folder and mark emails ~~ (원안)

Activations

In order to access courses, your account will need to be activated by staff.

```
If your account is not qualified for our terms of service, the activation would be denied.
```

The registration will be accepted for ~~~ only users  ~~~ (belong/parts of) the graduate schl?

**Comment by myoortcloud** [comment]
대학원생 분들이 알아서 한다고 합니다.
