### ISSUE TITLE
Index(Unauth): 비디오 링크가 포함된 hgroup

### ISSUE THREAD

**Issue by myoortcloud** [myoortcloud/kmu-edx#7]
![idx](https://cloud.githubusercontent.com/assets/6212926/3887414/65af6074-21f0-11e4-99c1-f4697b60c17c.png)

미인증 상태에서 Index 진입 시 파노라마 이미지에 오버레이로 표시되는 hgroup 컨텐츠 삭제.
- Pros
  KMU BIT edx의 지향점(폐쇄적인 계정운용 정책)과 다르기 때문에 삭제하는게 맞다.
  유튭 비디오 마땅한게 없다.
- Cons
  비어있으면 허전하다.
  edx-platform 레파지토리의 내용을 수정해야 한다.

**Comment by anqsdwe** [comment]
교수님이 지우라고 하셨습니다.
그리고 The Future of 저부분이랑
for anyone 저부분 글도 바꾸라고 하셨습니다.

**Comment by anqsdwe** [comment]
*edx-platform / lms / templates / index.html

파일의

```
          <h1>${_("The Future of Online Education")}</h1>

        <h2>${_("For anyone, anywhere, anytime")}</h2>
```

수정하겠습니다.

유투브 동영상 파일 부분은 같은 파일 내에

```
  % if show_homepage_promo_video:
```

a href="#video-modal" class="media" rel="leanModal">
          div class="hero">
            div class="play-intro"></div>
          /div>
        </a

부분입니다.

현재는 show_homepage_promo_video 변수를 false 시켜서 저 프로모선 비디오가 뜨지 않도록 할게요.

**Comment by anqsdwe** [comment]
![image](https://cloud.githubusercontent.com/assets/7992405/3930167/52517a12-2439-11e4-90bf-54b42ad86dcd.png)
